# Generated by Django 2.2.12 on 2020-08-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=48, verbose_name='Название')),
                ('_content', models.TextField(max_length=4000, verbose_name='Кантент')),
                ('_pub_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_author', models.CharField(max_length=36, verbose_name='Автор')),
                ('_content', models.TextField(max_length=400, verbose_name='Коментарий')),
                ('_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.Article')),
            ],
        ),
    ]
